############################################################
# Dockerfile 
############################################################
# Set the base image
FROM nginx
COPY dist /usr/share/nginx/html
