server:
  port: 10000
spring:
  application:
    name: api-gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:9000/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    resourse:
      service-id: tongqu-parser
      path: /resources/tongqu
  sensitive-headers: Cookie, Set-Cookie
management:
  endpoints:
    web:
      exposure:
        include: "*"

