spring:
  application:
    name: eureka-server
server:
  port: 9000
eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: false
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
